### ISSUE TITLE
How to use nrfutil.exe command-line tool to make a dfu with precompiled hex file for nRF52840 Dongle?

### ISSUE THREAD

**Issue by Droid-MAX** [mame82/LOGITacker#24]
I just follow this [README](https://github.com/NordicSemiconductor/pc-nrfutil/blob/master/README.md), then downloaded nrfutil.exe and execute it.
But it has three firmware types, I am really a little confused. So anyone can give me some help?

**Comment by Droid-MAX** [comment]
I want to pack hex to dfu zip package file, but there are some key parameters that are unclear, for example, the SDK version of SoftDevice.

**Comment by Droid-MAX** [comment]
![image](https://user-images.githubusercontent.com/12762435/65741631-5d79a600-e11f-11e9-89dc-1fc4e0a6c47f.png)

I have a very extreme network review in my area, so normal development work is very difficult to complete. This programmer plugin is stuck in the loading process even if I install it manually.

**Comment by Droid-MAX** [comment]
![image](https://user-images.githubusercontent.com/12762435/65744559-493ba600-e12b-11e9-8216-64f946baae64.png)

I even used several proxy tools, and they didn’t help.

**Comment by mame82** [comment]
Please file issues related to firmware flashing at support of the vendor 8f the specific board
