### ISSUE TITLE
Which version of SDK did you build?

### ISSUE THREAD

**Issue by mrguai** [mame82/LOGITacker#33]
Which version of SDK did you build?

**Comment by mame82** [comment]
SDK 15.3.0 (at time of this writing).

If you don't want to use the pre-built images, don't forget to adjust the SDK_ROOT in the respective Makefile

**Comment by mrguai** [comment]
> SDK 15.3.0 (at time of this writing).
> 
> If you don't want to use the pre-built images, don't forget to adjust the SDK_ROOT in the respective Makefile

ohh,thank you!! i did it!
