### ISSUE TITLE
Help tekst error

### ISSUE THREAD

**Issue by nieldk** [mame82/LOGITacker#8]
Minor error in 'option discover onhit' help text
Help text for passive-enum shoud read "enter **_passive_** enumeration mode", and not "enter **_active_** enumeration mode"

> 
> LOGITacker (discover) $ options discover onhit 
> onhit - select action to take when device a RF address is discovered
> Options:
>   -h, --help  :Show command help.
> Subcommands:
>   continue      :stay in discover mode.
>   active-enum   :enter active enumeration mode
>   passive-enum  :enter active enumeration mode
>   auto-inject   :enter injection mode and execute injection

**Comment by mame82** [comment]
fixed in v0.1.5
